# Generated by Django 5.1.2 on 2024-10-19 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('staking', 'staking out'), ('inventory', 'as-built inventory'), ('other', 'other')], max_length=16)),
                ('description', models.TextField(max_length=1024)),
                ('km_from', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('km_to', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('deadline', models.DateField()),
                ('comments', models.TextField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('refused', 'refused'), ('making_documents', 'making documents'), ('ready_to_stake_out', 'ready to stake out'), ('ongoing', 'ongoing'), ('finished', 'finished'), ('closed', 'closed')], default='waiting', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_contractor', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_principal', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.trade')),
            ],
        ),
    ]
