# Generated by Django 4.2.16 on 2024-11-20 21:40

import django.db.models.deletion
from django.db import migrations, models

import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=1024, upload_to=jobs.models.job_file_directory)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(default=None, null=True)),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
