# Generated by Django 5.1.1 on 2024-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(default='OT', max_length=2, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
